name: Test
on:
  push:
    branches:
      - main
  create:

jobs:
  build:
    name: Build and Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Get source code
        uses: actions/checkout@v1
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
      - name: release draft URL
        run: echo ${{ steps.create-release-draft.output.release-url }}
